services:
  - type: web
    name: owl-roles-backend
    dockerfile: Dockerfile.backend
    dockerfilePath: ./Dockerfile.backend
    buildContext: ./backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CLIENT_URL
        sync: false
  
  - type: web
    name: owl-roles-frontend
    dockerfile: Dockerfile.frontend
    dockerfilePath: ./Dockerfile.frontend
    buildContext: ./frontend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5174
      - key: VITE_API_END_POINT
        sync: false
      - key: VITE_CLOUDINARY_NAME
        sync: false
      - key: VITE_CLOUDINARY_PRESET
        sync: false
